### ISSUE TITLE
plotMonitor function issue (Sandia GridPV toolbox)

### ISSUE THREAD

**Issue by yaosuo** [dss-extensions/dss_matlab#18]

**Comment by yaosuo** [comment]
Modifying the gridpv codes to resolve the issue ...

**Comment by yaosuo** [comment]
To work with Sandia's GridPV toolbox, some quick minor changes are needed:
1) need to comment out the OpenDSS version check;
2) need to bypass the checking for a valid interface input, otherwise, more changes are needed to make it work, e.g. ispc shall change to ismac, etc.
With these change, OpenDSScmd, gridPV, dss_matlab can now run in mac-version Matlab.

**Comment by yaosuo** [comment]
done with my quick investigation

**Comment by PMeira** [comment]
Yeah, GridPV is kinda abandoned, it hasn't been updated in several years. Since it's distributed behind a form, I avoided hosting a modified/fixed copy. I should probably remove the mention the README. Thanks for the comments though, it could help someone else in the future.

On GridPV, some other functions won't work even with the official OpenDSS COM implementation on Windows, some due to changes in OpenDSS, some due to changes in MATLAB or outdated services (the map part). On the other hand, many parts still work fine.

> OpenDSScmd

Note that, currently, even though OpenDSScmd is distributed in the same site as the official Windows binaries, the macOS version of OpenDSScmd is not officially supported by EPRI, and it has some known issues. DSS_MATLAB is based on a different codebase which includes a lot of extra fixes for macOS and Linux.

**Comment by yaosuo** [comment]
You are doing interesting and great work!I just have some old codes from previous projects and was trying to make it work in the MacBook. Thanks!SonnySent from my iPhoneOn Mar 28, 2024, at 11:36 AM, Paulo Meira ***@***.***> wrote:﻿
Yeah, GridPV is kinda abandoned, it hasn't been updated in several years. Since it's distributed behind a form, I avoided hosting a modified/fixed copy. I should probably remove the mention the README. Thanks for the comments though, it could help someone else in the future.
On GridPV, some other functions won't work even with the official OpenDSS COM implementation on Windows, some due to changes in OpenDSS, some due to changes in MATLAB or outdated services (the map part). On the other hand, many parts still work fine.

OpenDSScmd

Note that, currently, even though OpenDSScmd is distributed in the same site as the official Windows binaries, the macOS version of OpenDSScmd is not officially supported by EPRI, and it has some known issues. DSS_MATLAB is based on a different codebase which includes a lot of extra fixes for macOS and Linux.

**Comment by yaosuo** [comment]
Do you mean dss_matlab has an implementation of KLUsolve and can work independently without opendsscmd, but follows the .dss conventions? That is a great thing!

**Comment by PMeira** [comment]
> Do you mean dss_matlab has an implementation of KLUsolve and can work independently without opendsscmd, but follows the .dss conventions? That is a great thing!

Yes, in fact our KLUSolve fork also has changes, one of them specifically to allow it to work on MATLAB on Linux and macOS (MATLAB includes a copy of most SuiteSparse packages and that can conflict with other software if it's handled not properly).

**Comment by PMeira** [comment]
For context, KLUSolve is basically a wrapper around KLU: https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/dev/KLU
